server:
  port: 8070
spring:
  profiles:
    active: prod
  application:
   name: service-study-provider
  cloud:
    nacos:
#      server-addr: 10.20.25.20:8848
      server-addr: 127.0.0.1:8848
      username: app-exchange
      password: 123456
      discovery:
        # 服务统一注册到 public 中，否则无法被其他的命名空间下的项目感知到
        namespace: 71efc714-a6d7-4a21-8180-614e38a33403
        group: ${spring.profiles.active:prod}  # group分成 dev/test/prod
#        server-addr:  127.0.0.1:9876
#        service: ${spring.application.name}