server:
  port: 8070
spring:
  application:
   name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.13:8848
        service: ${spring.application.name}
debug: true