server:
  port: 8075
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      server-addr: 10.5.113.38:8848
      username: app-exchange
      password: 123456
      discovery:
        namespace: 745f3022-9c9e-4795-9217-040aaf6f18d9
        group: ${spring.profiles.active:prod}  # group分成 dev/test/prod